apiVersion: v1
kind: Pod
metadata: 
  name: multiple-containers
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux9
      image: almalinux:9
      command: ["sleep", "1000"]