apiVersion: v1
kind: Pod
metadata:
  name: labels
  namespace: expense
  labels:
    projects: expense
    components: backend
    environments: dev
spec:
  containers:
  - name: nginx
    image: nginx
    