apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    buildURL: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://hub.docker.com/"
    description: "This pod runs nginx"
    owner: "dev-team"
spec:
  containers:
  - name: nginx
    image: nginx